name: "olist_ecommerce_dbt"
version: "1.0.0"

profile: "olist_ecommerce_dbt"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  olist_ecommerce_dbt:
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    mart:
      +schema: mart
